frase = 'Curso em Video Python'
print(frase.lower())
print(frase.upper())
print(frase.find('o'))
print(frase.count('o', 0, 13))
print(frase.count('o'))
print(frase.find('urso'))
print('Curso' in frase)
print(frase.replace('Python', 'Java'))
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.split())
('-').join(frase)
