print('-=-' * 20)
print('Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todos as informações possiveis sobre ele.')
print('-=-' * 20)
a = input('Digite algo: ')
print ('O tipo primitivo desse valor é:', type(a))
print ('Só espaços?', a.isspace())
print ('Esta em minúsculas?', a.islower())
print ('Esta em maiúsculas?', a.isupper())
print ('Tem números?', a.isnumeric())
print ('É alfabético?', a.isalpha())
print ('É alphanúmerico?', a.isalnum())
print ('Está capitalizada? ', a.istitle())